default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cars_market_development

test:
  <<: *default
  database: cars_market_test

production:
  <<: *default
  database: cars_market_production
  username: cars_market
  password: <%= ENV["CARS_MARKET_DATABASE_PASSWORD"] %>
